# Generated by Django 4.1.6 on 2023-02-12 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='release_date',
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
